In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
Dataset=pd.read_csv("insurance_pre.csv")

In [4]:
Dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [5]:
Dataset=pd.get_dummies(Dataset,dtype=int,drop_first=True)

In [6]:
Dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
Independent=Dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
Dependent=Dataset[['charges']]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [10]:
print(X_train)

[[-1.5330973  -0.40713453 -0.89833872 -0.97676557 -0.50466988]
 [-0.03364163  0.32855417 -0.89833872 -0.97676557 -0.50466988]
 [ 0.89459283  2.56690911  3.25603402 -0.97676557 -0.50466988]
 ...
 [ 0.03776102 -0.91016269 -0.89833872  1.02378711 -0.50466988]
 [-1.46169465  0.76659782 -0.89833872  1.02378711 -0.50466988]
 [-0.46205754 -1.96596021 -0.06746417 -0.97676557 -0.50466988]]


In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    'kernel': ['rbf', 'poly', 'sigmoid', 'linear'],
    'C': [10, 1000, 2000, 3000],
    'gamma': ['auto', 'scale']
}

grid= GridSearchCV(SVR(),param_grid, refit=True,verbose=3, n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits


c:\Users\Gajalakshmi G\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for the best parameter {}:".format(grid.best_params_))

The R_score value for the best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:


In [13]:
table=pd.DataFrame.from_dict(re)


In [24]:
print(table.head(10))

   mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.056064      0.005074         0.035523        0.002362      10   
1       0.043192      0.003233         0.007353        0.000746      10   
2       0.057425      0.002632         0.013813        0.004371      10   
3       0.041797      0.003723         0.006858        0.001073      10   
4       0.053730      0.003288         0.038734        0.003354      10   
5       0.041151      0.000996         0.007290        0.000682      10   
6       0.062841      0.001801         0.013158        0.001718      10   
7       0.043407      0.004755         0.007176        0.001933      10   
8       0.069615      0.002630         0.037891        0.003532    1000   
9       0.074258      0.015914         0.007356        0.000853    1000   

  param_gamma param_kernel                                            params  \
0        auto          rbf       {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
1        auto 

In [20]:
age_input = float(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = float(input("Children: "))
Sex_male_input=int(input("sex male 0 or 1: "))
smoker_yes_input=int(input("Smoker yes 0 or 1: "))

In [21]:
Future_prediction=grid.predict([[age_input,bmi_input,children_input,Sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_prediction))

Future_Prediction=[2291197.32937815]
